server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #路由的id，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #匹配后提供服务的路由地址
          uri: lb://cloud-paymant-service
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-paymant-service
          #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id，值为1024
#          filters:
#            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/lb/**
            #- After=2020-05-16T11:03:16.126+08:00[Asia/Shanghai]
            #- Before=2020-05-16T12:03:16.126+08:00[Asia/Shanghai]
            #- Between=2020-05-16T11:03:16.126+08:00[Asia/Shanghai],2020-05-16T12:03:16.126+08:00[Asia/Shanghai]
            #- Cookie=username,lenovo
            #请求头要有X-request-Id属性并且值为正数的正则表达式
            #- Header=X-Request-Id, \d+
            #- Host=**.atguigu.com
            - Method=GET
eureka:
  instance:
    hostname: cloud-gateway-service
#  client:
#    service-url:
#      register-with-eureka: true
#      fetch-registry: true
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  client:
    #表示是否将自己注册进eurekaServer，默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
